print("welcome to Ashtech ultaa phulta shabd")
print("Enter your name")
output1=input()
print("Ok",(output1))
print((output1),"Just enter your word to make its spelling opposite" )
output2=input()
mystr=(output2)
print(mystr[::-1])
print("OK",(output1),"thanks for use it Bye Bye")

output3=input("Enter your favourite word")